spring:
  application:
    name: rest
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/testDb
    username: cpc
    password: q1w2e3r4
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:/db/migration
    schemas: testDb
    url: jdbc:h2:mem:testDb
    baseline-on-migrate: true
    
#http://localhost:8080/swagger-ui.html
